import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Heading from "../components/heading";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <Heading text='Hi Jack!' tag={'h1'}/>
            </main>

        </>
    )
}
